import { Waypoints } from 'lucide-react';
import { type Topic } from './types';

export const linearAlgebraTopics: Topic[] = [
  {
    id: 'linear-equation-systems',
    title: 'Chapter 1: Linear Equation Systems',
    href: '/topics/linear-algebra/linear-equation-systems',
    icon: Waypoints,
    description:
      'What is a Linear System?, Geometric Interpretation in 2D and 3D, Solving Systems with Gaussian Elimination, Row Echelon Form (REF) and Reduced Row Echelon Form (RREF), Existence and Uniqueness of Solutions',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      { id: 'what-is-a-linear-system', title: 'What is a Linear System?' },
      {
        id: 'geometric-interpretation',
        title: 'Geometric Interpretation in 2D & 3D',
      },
      {
        id: 'gaussian-elimination',
        title: 'Solving with Gaussian Elimination',
      },
      { id: 'echelon-forms', title: 'Row Echelon Form (REF & RREF)' },
      {
        id: 'existence-uniqueness',
        title: 'Existence and Uniqueness of Solutions',
      },
    ],
  },
  {
    id: 'what-is-a-linear-system',
    title: 'What is a Linear System?',
    href: '/topics/what-is-a-linear-system',
    icon: Waypoints,
    description: 'An introduction to systems of linear equations.',
    category: 'sub-topic',
    parent: 'linear-equation-systems',
  },
  {
    id: 'geometric-interpretation',
    title: 'Geometric Interpretation in 2D & 3D',
    href: '/topics/geometric-interpretation',
    icon: Waypoints,
    description: 'Visualizing linear systems as lines and planes.',
    category: 'sub-topic',
    parent: 'linear-equation-systems',
  },
  {
    id: 'echelon-forms',
    title: 'Row Echelon Form (REF & RREF)',
    href: '/topics/echelon-forms',
    icon: Waypoints,
    description: 'Understanding the standard forms of matrices for solving systems.',
    category: 'sub-topic',
    parent: 'linear-equation-systems',
  },
  {
    id: 'existence-uniqueness',
    title: 'Existence and Uniqueness of Solutions',
    href: '/topics/existence-uniqueness',
    icon: Waypoints,
    description: 'Determining the nature of solutions to a linear system.',
    category: 'sub-topic',
    parent: 'linear-equation-systems',
  },
  {
    id: 'basic-matrix-algebra',
    title: 'Chapter 2: Basic Matrix Algebra',
    href: '/topics/linear-algebra/basic-matrix-algebra',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      { id: 'matrix-notation', title: 'Matrix Notation and Terminology' },
      {
        id: 'matrix-operations',
        title: 'Matrix Addition, Subtraction, and Scalar Multiplication',
      },
      {
        id: 'matrix-multiplication',
        title: 'Matrix Multiplication and its Properties',
      },
      {
        id: 'transpose-and-inverse',
        title: 'The Transpose and the Inverse of a Matrix',
      },
      {
        id: 'special-matrices',
        title: 'Special Matrices: Identity, Zero, Diagonal, Symmetric',
      },
    ],
  },
  {
    id: 'matrix-notation',
    title: 'Matrix Notation and Terminology',
    href: '/topics/matrix-notation',
    icon: Waypoints,
    description: 'Understanding the basic notation and terms for matrices.',
    category: 'sub-topic',
    parent: 'basic-matrix-algebra',
  },
  {
    id: 'matrix-operations',
    title: 'Matrix Addition, Subtraction, and Scalar Multiplication',
    href: '/topics/matrix-operations',
    icon: Waypoints,
    description: 'Performing basic arithmetic operations on matrices.',
    category: 'sub-topic',
    parent: 'basic-matrix-algebra',
  },
  {
    id: 'matrix-multiplication',
    title: 'Matrix Multiplication and its Properties',
    href: '/topics/matrix-multiplication',
    icon: Waypoints,
    description: 'Understanding the rules and properties of multiplying matrices.',
    category: 'sub-topic',
    parent: 'basic-matrix-algebra',
  },
  {
    id: 'transpose-and-inverse',
    title: 'The Transpose and the Inverse of a Matrix',
    href: '/topics/transpose-and-inverse',
    icon: Waypoints,
    description: 'Learning about two fundamental matrix operations.',
    category: 'sub-topic',
    parent: 'basic-matrix-algebra',
  },
  {
    id: 'special-matrices',
    title: 'Special Matrices: Identity, Zero, Diagonal, Symmetric',
    href: '/topics/special-matrices',
    icon: Waypoints,
    description: 'An overview of important types of matrices.',
    category: 'sub-topic',
    parent: 'basic-matrix-algebra',
  },
  {
    id: 'determinants-and-lu-factorization',
    title: 'Chapter 3: Determinants and LU Factorization',
    href: '/topics/linear-algebra/determinants-and-lu-factorization',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      {
        id: 'calculating-determinants',
        title: 'Calculating Determinants using Cofactor Expansion',
      },
      {
        id: 'properties-of-determinants',
        title: 'Properties of Determinants',
      },
      {
        id: 'determinant-and-invertibility',
        title: 'Relationship between Determinant and Invertibility',
      },
      {
        id: 'lu-factorization-intro',
        title: 'Introduction to LU Factorization',
      },
      {
        id: 'solving-systems-with-lu',
        title: 'Solving Systems Efficiently with LU Factorization',
      },
    ],
  },
  {
    id: 'calculating-determinants',
    title: 'Calculating Determinants using Cofactor Expansion',
    href: '/topics/calculating-determinants',
    icon: Waypoints,
    description: 'A method for computing the determinant of a matrix.',
    category: 'sub-topic',
    parent: 'determinants-and-lu-factorization',
  },
  {
    id: 'properties-of-determinants',
    title: 'Properties of Determinants',
    href: '/topics/properties-of-determinants',
    icon: Waypoints,
    description: 'Key properties that simplify determinant calculations.',
    category: 'sub-topic',
    parent: 'determinants-and-lu-factorization',
  },
  {
    id: 'determinant-and-invertibility',
    title: 'Relationship between Determinant and Invertibility',
    href: '/topics/determinant-and-invertibility',
    icon: Waypoints,
    description: 'How the determinant tells us if a matrix is invertible.',
    category: 'sub-topic',
    parent: 'determinants-and-lu-factorization',
  },
  {
    id: 'lu-factorization-intro',
    title: 'Introduction to LU Factorization',
    href: '/topics/lu-factorization-intro',
    icon: Waypoints,
    description: 'Decomposing a matrix into lower and upper triangular matrices.',
    category: 'sub-topic',
    parent: 'determinants-and-lu-factorization',
  },
  {
    id: 'solving-systems-with-lu',
    title: 'Solving Systems Efficiently with LU Factorization',
    href: '/topics/solving-systems-with-lu',
    icon: Waypoints,
    description: 'Using LU factorization to solve systems of linear equations.',
    category: 'sub-topic',
    parent: 'determinants-and-lu-factorization',
  },
  {
    id: 'vector-operations-and-linear-combinations',
    title: 'Chapter 4: Vector Operations and Linear Combinations',
    href: '/topics/linear-algebra/vector-operations-and-linear-combinations',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      {
        id: 'vectors-in-rn',
        title: 'Vectors in Rn (Geometric and Algebraic Views)',
      },
      {
        id: 'vector-operations',
        title: 'Vector Addition, Subtraction, and Scalar Multiplication',
      },
      { id: 'linear-combinations', title: 'Linear Combinations and Weights' },
      { id: 'span', title: 'The concept of Span' },
    ],
  },
  {
    id: 'vectors-in-rn',
    title: 'Vectors in Rn (Geometric and Algebraic Views)',
    href: '/topics/vectors-in-rn',
    icon: Waypoints,
    description: 'Understanding vectors in n-dimensional space.',
    category: 'sub-topic',
    parent: 'vector-operations-and-linear-combinations',
  },
  {
    id: 'vector-operations',
    title: 'Vector Addition, Subtraction, and Scalar Multiplication',
    href: '/topics/vector-operations',
    icon: Waypoints,
    description: 'Performing basic arithmetic operations on vectors.',
    category: 'sub-topic',
    parent: 'vector-operations-and-linear-combinations',
  },
  {
    id: 'linear-combinations',
    title: 'Linear Combinations and Weights',
    href: '/topics/linear-combinations',
    icon: Waypoints,
    description: 'Combining vectors using scalar multiplication and addition.',
    category: 'sub-topic',
    parent: 'vector-operations-and-linear-combinations',
  },
  {
    id: 'span',
    title: 'The concept of Span',
    href: '/topics/span',
    icon: Waypoints,
    description: 'Understanding the set of all possible linear combinations of a set of vectors.',
    category: 'sub-topic',
    parent: 'vector-operations-and-linear-combinations',
  },
  {
    id: 'linear-independence-vector-spaces-and-subspaces',
    title: 'Chapter 5: Linear Independence, Vector Spaces, and Subspaces',
    href: '/topics/linear-algebra/linear-independence-vector-spaces-and-subspaces',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      {
        id: 'linear-independence-definition',
        title: 'Definition of Linear Independence and Dependence',
      },
      {
        id: 'vector-space-definition',
        title: 'The Formal Definition of a Vector Space and its Axioms',
      },
      {
        id: 'subspace-test',
        title: 'What is a Subspace? The Subspace Test',
      },
    ],
  },
  {
    id: 'linear-independence-definition',
    title: 'Definition of Linear Independence and Dependence',
    href: '/topics/linear-independence-definition',
    icon: Waypoints,
    description: 'Determining if a set of vectors is linearly independent.',
    category: 'sub-topic',
    parent: 'linear-independence-vector-spaces-and-subspaces',
  },
  {
    id: 'vector-space-definition',
    title: 'The Formal Definition of a Vector Space and its Axioms',
    href: '/topics/vector-space-definition',
    icon: Waypoints,
    description: 'Understanding the properties that define a vector space.',
    category: 'sub-topic',
    parent: 'linear-independence-vector-spaces-and-subspaces',
  },
  {
    id: 'subspace-test',
    title: 'What is a Subspace? The Subspace Test',
    href: '/topics/subspace-test',
    icon: Waypoints,
    description: 'How to determine if a subset of a vector space is a subspace.',
    category: 'sub-topic',
    parent: 'linear-independence-vector-spaces-and-subspaces',
  },
  {
    id: 'basis-dimension-and-four-fundamental-subspaces',
    title: 'Chapter 6: Basis, Dimension, and the Four Fundamental Subspaces',
    href: '/topics/linear-algebra/basis-dimension-and-four-fundamental-subspaces',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      { id: 'basis-definition', title: 'The Definition of a Basis' },
      {
        id: 'coordinates-of-a-vector',
        title: 'Coordinates of a Vector Relative to a Basis',
      },
      {
        id: 'dimension-of-vector-space',
        title: 'Dimension of a Vector Space',
      },
      {
        id: 'four-fundamental-subspaces',
        title:
          'The Four Fundamental Subspaces: Column, Row, Null, and Left Null Space',
      },
      {
        id: 'rank-nullity-theorem',
        title: 'Rank of a Matrix and the Rank-Nullity Theorem',
      },
    ],
  },
  {
    id: 'basis-definition',
    title: 'The Definition of a Basis',
    href: '/topics/basis-definition',
    icon: Waypoints,
    description: 'Understanding what constitutes a basis for a vector space.',
    category: 'sub-topic',
    parent: 'basis-dimension-and-four-fundamental-subspaces',
  },
  {
    id: 'coordinates-of-a-vector',
    title: 'Coordinates of a Vector Relative to a Basis',
    href: '/topics/coordinates-of-a-vector',
    icon: Waypoints,
    description: 'Representing vectors in terms of a specific basis.',
    category: 'sub-topic',
    parent: 'basis-dimension-and-four-fundamental-subspaces',
  },
  {
    id: 'dimension-of-vector-space',
    title: 'Dimension of a Vector Space',
    href: '/topics/dimension-of-vector-space',
    icon: Waypoints,
    description: 'Defining the dimension of a vector space.',
    category: 'sub-topic',
    parent: 'basis-dimension-and-four-fundamental-subspaces',
  },
  {
    id: 'four-fundamental-subspaces',
    title: 'The Four Fundamental Subspaces: Column, Row, Null, and Left Null Space',
    href: '/topics/four-fundamental-subspaces',
    icon: Waypoints,
    description: 'Exploring the four key subspaces associated with a matrix.',
    category: 'sub-topic',
    parent: 'basis-dimension-and-four-fundamental-subspaces',
  },
  {
    id: 'rank-nullity-theorem',
    title: 'Rank of a Matrix and the Rank-Nullity Theorem',
    href: '/topics/rank-nullity-theorem',
    icon: Waypoints,
    description: 'Understanding the relationship between the rank and nullity of a matrix.',
    category: 'sub-topic',
    parent: 'basis-dimension-and-four-fundamental-subspaces',
  },
  {
    id: 'linear-transformations',
    title: 'Chapter 7: Linear Transformations',
    href: '/topics/linear-algebra/linear-transformations',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      {
        id: 'linear-transformations-intro',
        title: 'Introduction to Linear Transformations',
      },
      {
        id: 'matrix-of-a-linear-transformation',
        title: 'The Matrix of a Linear Transformation',
      },
      {
        id: 'geometric-transformations',
        title: 'Geometric Transformations: Rotations, Reflections, Projections',
      },
      {
        id: 'kernel-and-range',
        title:
          'Kernel (Null Space) and Range (Column Space) of a Transformation',
      },
    ],
  },
  {
    id: 'linear-transformations-intro',
    title: 'Introduction to Linear Transformations',
    href: '/topics/linear-transformations-intro',
    icon: Waypoints,
    description: 'Understanding functions that map vectors to other vectors.',
    category: 'sub-topic',
    parent: 'linear-transformations',
  },
  {
    id: 'matrix-of-a-linear-transformation',
    title: 'The Matrix of a Linear Transformation',
    href: '/topics/matrix-of-a-linear-transformation',
    icon: Waypoints,
    description: 'Representing linear transformations with matrices.',
    category: 'sub-topic',
    parent: 'linear-transformations',
  },
  {
    id: 'geometric-transformations',
    title: 'Geometric Transformations: Rotations, Reflections, Projections',
    href: '/topics/geometric-transformations',
    icon: Waypoints,
    description: 'Visualizing linear transformations in geometric terms.',
    category: 'sub-topic',
    parent: 'linear-transformations',
  },
  {
    id: 'kernel-and-range',
    title: 'Kernel (Null Space) and Range (Column Space) of a Transformation',
    href: '/topics/kernel-and-range',
    icon: Waypoints,
    description: 'Understanding the input and output spaces of a linear transformation.',
    category: 'sub-topic',
    parent: 'linear-transformations',
  },
  {
    id: 'inner-products-and-orthogonality',
    title: 'Chapter 8: Inner Products and Orthogonality',
    href: '/topics/linear-algebra/inner-products-and-orthogonality',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      {
        id: 'dot-product-norm-distance',
        title: 'The Dot Product, Vector Length (Norm), and Distance',
      },
      {
        id: 'orthogonal-vectors-complements',
        title: 'Orthogonal Vectors and Orthogonal Complements',
      },
      {
        id: 'orthogonal-sets',
        title: 'Orthogonal and Orthonormal Sets',
      },
      {
        id: 'orthogonal-projections',
        title: 'Orthogonal Projections',
      },
    ],
  },
  {
    id: 'dot-product-norm-distance',
    title: 'The Dot Product, Vector Length (Norm), and Distance',
    href: '/topics/dot-product-norm-distance',
    icon: Waypoints,
    description: 'Calculating the dot product, norm, and distance for vectors.',
    category: 'sub-topic',
    parent: 'inner-products-and-orthogonality',
  },
  {
    id: 'orthogonal-vectors-complements',
    title: 'Orthogonal Vectors and Orthogonal Complements',
    href: '/topics/orthogonal-vectors-complements',
    icon: Waypoints,
    description: 'Understanding perpendicular vectors and their complements.',
    category: 'sub-topic',
    parent: 'inner-products-and-orthogonality',
  },
  {
    id: 'orthogonal-sets',
    title: 'Orthogonal and Orthonormal Sets',
    href: '/topics/orthogonal-sets',
    icon: Waypoints,
    description: 'Working with sets of orthogonal and orthonormal vectors.',
    category: 'sub-topic',
    parent: 'inner-products-and-orthogonality',
  },
  {
    id: 'orthogonal-projections',
    title: 'Orthogonal Projections',
    href: '/topics/orthogonal-projections',
    icon: Waypoints,
    description: 'Projecting one vector onto another.',
    category: 'sub-topic',
    parent: 'inner-products-and-orthogonality',
  },
  {
    id: 'gram-schmidt-process-and-qr-decomposition',
    title: 'Chapter 9: The Gram-Schmidt Process and QR Decomposition',
    href: '/topics/linear-algebra/gram-schmidt-process-and-qr-decomposition',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      {
        id: 'gram-schmidt-process',
        title: 'The Gram-Schmidt Process for Creating an Orthonormal Basis',
      },
      {
        id: 'qr-decomposition',
        title: 'QR Decomposition of a Matrix',
      },
      {
        id: 'application-least-squares',
        title: 'Application: Least-Squares Problems and Linear Regression',
      },
    ],
  },
  {
    id: 'gram-schmidt-process',
    title: 'The Gram-Schmidt Process for Creating an Orthonormal Basis',
    href: '/topics/gram-schmidt-process',
    icon: Waypoints,
    description: 'A method for orthonormalizing a set of vectors.',
    category: 'sub-topic',
    parent: 'gram-schmidt-process-and-qr-decomposition',
  },
  {
    id: 'qr-decomposition',
    title: 'QR Decomposition of a Matrix',
    href: '/topics/qr-decomposition',
    icon: Waypoints,
    description: 'Decomposing a matrix into an orthogonal and an upper triangular matrix.',
    category: 'sub-topic',
    parent: 'gram-schmidt-process-and-qr-decomposition',
  },
  {
    id: 'application-least-squares',
    title: 'Application: Least-Squares Problems and Linear Regression',
    href: '/topics/application-least-squares',
    icon: Waypoints,
    description: 'Using QR decomposition to solve least-squares problems.',
    category: 'sub-topic',
    parent: 'gram-schmidt-process-and-qr-decomposition',
  },
  {
    id: 'eigenvalues-and-eigenvectors',
    title: 'Chapter 10: Eigenvalues and Eigenvectors',
    href: '/topics/linear-algebra/eigenvalues-and-eigenvectors',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      {
        id: 'eigenvalues-eigenvectors-definition',
        title: 'Definition of Eigenvalues and Eigenvectors',
      },
      {
        id: 'characteristic-equation',
        title: 'The Characteristic Equation',
      },
      { id: 'eigenspaces', title: 'Eigenspaces' },
      {
        id: 'eigenvalues-of-special-matrices',
        title: 'Eigenvalues of Special Matrices',
      },
    ],
  },
  {
    id: 'eigenvalues-eigenvectors-definition',
    title: 'Definition of Eigenvalues and Eigenvectors',
    href: '/topics/eigenvalues-eigenvectors-definition',
    icon: Waypoints,
    description: 'Understanding the fundamental concepts of eigenvalues and eigenvectors.',
    category: 'sub-topic',
    parent: 'eigenvalues-and-eigenvectors',
  },
  {
    id: 'characteristic-equation',
    title: 'The Characteristic Equation',
    href: '/topics/characteristic-equation',
    icon: Waypoints,
    description: 'How to find eigenvalues using the characteristic equation.',
    category: 'sub-topic',
    parent: 'eigenvalues-and-eigenvectors',
  },
  {
    id: 'eigenspaces',
    title: 'Eigenspaces',
    href: '/topics/eigenspaces',
    icon: Waypoints,
    description: 'Understanding the vector space spanned by eigenvectors.',
    category: 'sub-topic',
    parent: 'eigenvalues-and-eigenvectors',
  },
  {
    id: 'eigenvalues-of-special-matrices',
    title: 'Eigenvalues of Special Matrices',
    href: '/topics/eigenvalues-of-special-matrices',
    icon: Waypoints,
    description: 'Eigenvalues for common types of matrices.',
    category: 'sub-topic',
    parent: 'eigenvalues-and-eigenvectors',
  },
  {
    id: 'diagonalization-and-applications-to-dynamic-systems',
    title: 'Chapter 11: Diagonalization and Applications to Dynamic Systems',
    href: '/topics/linear-algebra/diagonalization-and-applications-to-dynamic-systems',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      {
        id: 'diagonalization-theorem',
        title: 'The Diagonalization Theorem: A = PDP-1',
      },
      {
        id: 'conditions-for-diagonalizability',
        title: 'Conditions for Diagonalizability',
      },
      {
        id: 'application-computing-high-powers',
        title: 'Application: Computing High Powers of a Matrix',
      },
      {
        id: 'application-dynamic-systems-markov-chains',
        title: 'Application: Modeling Dynamic Systems and Markov Chains',
      },
    ],
  },
  {
    id: 'diagonalization-theorem',
    title: 'The Diagonalization Theorem: A = PDP-1',
    href: '/topics/diagonalization-theorem',
    icon: Waypoints,
    description: 'Understanding how to diagonalize a matrix.',
    category: 'sub-topic',
    parent: 'diagonalization-and-applications-to-dynamic-systems',
  },
  {
    id: 'conditions-for-diagonalizability',
    title: 'Conditions for Diagonalizability',
    href: '/topics/conditions-for-diagonalizability',
    icon: Waypoints,
    description: 'When a matrix can be diagonalized.',
    category: 'sub-topic',
    parent: 'diagonalization-and-applications-to-dynamic-systems',
  },
  {
    id: 'application-computing-high-powers',
    title: 'Application: Computing High Powers of a Matrix',
    href: '/topics/application-computing-high-powers',
    icon: Waypoints,
    description: 'Using diagonalization to efficiently compute matrix powers.',
    category: 'sub-topic',
    parent: 'diagonalization-and-applications-to-dynamic-systems',
  },
  {
    id: 'application-dynamic-systems-markov-chains',
    title: 'Application: Modeling Dynamic Systems and Markov Chains',
    href: '/topics/application-dynamic-systems-markov-chains',
    icon: Waypoints,
    description: 'Applying diagonalization to model systems that evolve over time.',
    category: 'sub-topic',
    parent: 'diagonalization-and-applications-to-dynamic-systems',
  },
  {
    id: 'symmetric-matrices-quadratic-forms-cholesky-decomposition',
    title:
      'Chapter 12: Symmetric Matrices, Quadratic Forms, and Cholesky Decomposition',
    href:
      '/topics/linear-algebra/symmetric-matrices-quadratic-forms-cholesky-decomposition',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      {
        id: 'diagonalization-of-symmetric-matrices',
        title:
          'Properties and Diagonalization of Symmetric Matrices (The Spectral Theorem)',
      },
      {
        id: 'quadratic-forms-positive-definite',
        title: 'Quadratic Forms and Positive Definite Matrices',
      },
      {
        id: 'application-portfolio-optimization',
        title:
          'Application: Markowitz Portfolio Optimization and the Efficient Frontier',
      },
      {
        id: 'application-cholesky-decomposition',
        title:
          'Application: Cholesky Decomposition for Monte Carlo Simulation',
      },
    ],
  },
  {
    id: 'diagonalization-of-symmetric-matrices',
    title:
      'Properties and Diagonalization of Symmetric Matrices (The Spectral Theorem)',
    href: '/topics/diagonalization-of-symmetric-matrices',
    icon: Waypoints,
    description: 'A key theorem for symmetric matrices.',
    category: 'sub-topic',
    parent: 'symmetric-matrices-quadratic-forms-cholesky-decomposition',
  },
  {
    id: 'quadratic-forms-positive-definite',
    title: 'Quadratic Forms and Positive Definite Matrices',
    href: '/topics/quadratic-forms-positive-definite',
    icon: Waypoints,
    description: 'Understanding quadratic forms and their relationship to matrices.',
    category: 'sub-topic',
    parent: 'symmetric-matrices-quadratic-forms-cholesky-decomposition',
  },
  {
    id: 'application-portfolio-optimization',
    title:
      'Application: Markowitz Portfolio Optimization and the Efficient Frontier',
    href: '/topics/application-portfolio-optimization',
    icon: Waypoints,
    description: 'Using linear algebra to optimize investment portfolios.',
    category: 'sub-topic',
    parent: 'symmetric-matrices-quadratic-forms-cholesky-decomposition',
  },
  {
    id: 'application-cholesky-decomposition',
    title:
      'Application: Cholesky Decomposition for Monte Carlo Simulation',
    href: '/topics/application-cholesky-decomposition',
    icon: Waypoints,
    description: 'A technique for generating correlated random variables.',
    category: 'sub-topic',
    parent: 'symmetric-matrices-quadratic-forms-cholesky-decomposition',
  },
  {
    id: 'singular-value-decomposition-svd',
    title: 'Chapter 13: The Singular Value Decomposition (SVD)',
    href: '/topics/linear-algebra/singular-value-decomposition-svd',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      { id: 'geometry-of-svd', title: 'The Geometry of SVD' },
      { id: 'constructing-the-svd', title: 'Constructing the SVD' },
      {
        id: 'application-noise-reduction',
        title: 'Application: Noise Reduction in Financial Time Series',
      },
      {
        id: 'application-dimensionality-reduction',
        title: 'Application: Dimensionality Reduction',
      },
    ],
  },
  {
    id: 'geometry-of-svd',
    title: 'The Geometry of SVD',
    href: '/topics/geometry-of-svd',
    icon: Waypoints,
    description: 'Visualizing the singular value decomposition.',
    category: 'sub-topic',
    parent: 'singular-value-decomposition-svd',
  },
  {
    id: 'constructing-the-svd',
    title: 'Constructing the SVD',
    href: '/topics/constructing-the-svd',
    icon: Waypoints,
    description: 'The process of finding the SVD of a matrix.',
    category: 'sub-topic',
    parent: 'singular-value-decomposition-svd',
  },
  {
    id: 'application-noise-reduction',
    title: 'Application: Noise Reduction in Financial Time Series',
    href: '/topics/application-noise-reduction',
    icon: Waypoints,
    description: 'Using SVD to filter out noise from financial data.',
    category: 'sub-topic',
    parent: 'singular-value-decomposition-svd',
  },
  {
    id: 'application-dimensionality-reduction',
    title: 'Application: Dimensionality Reduction',
    href: '/topics/application-dimensionality-reduction',
    icon: Waypoints,
    description: 'Reducing the number of variables in a dataset using SVD.',
    category: 'sub-topic',
    parent: 'singular-value-decomposition-svd',
  },
  {
    id: 'principal-component-analysis-pca',
    title: 'Chapter 14: Principal Component Analysis (PCA)',
    href: '/topics/linear-algebra/principal-component-analysis-pca',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      { id: 'covariance-matrix', title: 'The Covariance Matrix' },
      {
        id: 'finding-principal-components',
        title: 'Finding Principal Components using Eigendecomposition',
      },
      {
        id: 'geometric-interpretation-of-pca',
        title: 'Geometric Interpretation of PCA',
      },
      {
        id: 'application-discovering-risk-factors',
        title:
          'Application: Discovering Hidden Statistical Risk Factors in Asset Returns',
      },
    ],
  },
  {
    id: 'covariance-matrix',
    title: 'The Covariance Matrix',
    href: '/topics/the-covariance-matrix',
    icon: Waypoints,
    description: 'A matrix representing the covariance between elements of a random vector.',
    category: 'sub-topic',
    parent: 'principal-component-analysis-pca',
  },
  {
    id: 'finding-principal-components',
    title: 'Finding Principal Components using Eigendecomposition',
    href: '/topics/finding-principal-components',
    icon: Waypoints,
    description: 'Using eigenvalues and eigenvectors to find principal components.',
    category: 'sub-topic',
    parent: 'principal-component-analysis-pca',
  },
  {
    id: 'geometric-interpretation-of-pca',
    title: 'Geometric Interpretation of PCA',
    href: '/topics/geometric-interpretation-of-pca',
    icon: Waypoints,
    description: 'Visualizing PCA as a rotation of the coordinate system.',
    category: 'sub-topic',
    parent: 'principal-component-analysis-pca',
  },
  {
    id: 'application-discovering-risk-factors',
    title:
      'Application: Discovering Hidden Statistical Risk Factors in Asset Returns',
    href: '/topics/application-discovering-risk-factors',
    icon: Waypoints,
    description: 'Using PCA to identify underlying risk factors in financial markets.',
    category: 'sub-topic',
    parent: 'principal-component-analysis-pca',
  },
  {
    id: 'multivariate-normal-distribution',
    title: 'Chapter 15: The Multivariate Normal Distribution',
    href: '/topics/linear-algebra/multivariate-normal-distribution',
    icon: Waypoints,
    description: '',
    category: 'sub-topic',
    parent: 'la-main-chapters',
    subTopics: [
      {
        id: 'mean-vector-and-covariance-matrix',
        title: 'The Mean Vector and Covariance Matrix',
      },
      {
        id: 'probability-density-function',
        title: 'The Probability Density Function (PDF)',
      },
      {
        id: 'geometric-interpretation-ellipsoidal-contours',
        title: 'Geometric Interpretation: Ellipsoidal Contours',
      },
      {
        id: 'application-modeling-joint-asset-returns',
        title: 'Application: Modeling Joint Asset Returns and Portfolio Risk',
      },
    ],
  },
  {
    id: 'mean-vector-and-covariance-matrix',
    title: 'The Mean Vector and Covariance Matrix',
    href: '/topics/mean-vector-and-covariance-matrix',
    icon: Waypoints,
    description: 'Parameters of the multivariate normal distribution.',
    category: 'sub-topic',
    parent: 'multivariate-normal-distribution',
  },
  {
    id: 'probability-density-function',
    title: 'The Probability Density Function (PDF)',
    href: '/topics/probability-density-function',
    icon: Waypoints,
    description: 'The formula for the multivariate normal PDF.',
    category: 'sub-topic',
    parent: 'multivariate-normal-distribution',
  },
  {
    id: 'geometric-interpretation-ellipsoidal-contours',
    title: 'Geometric Interpretation: Ellipsoidal Contours',
    href: '/topics/geometric-interpretation-ellipsoidal-contours',
    icon: Waypoints,
    description: 'Visualizing the multivariate normal distribution.',
    category: 'sub-topic',
    parent: 'multivariate-normal-distribution',
  },
  {
    id: 'application-modeling-joint-asset-returns',
    title: 'Application: Modeling Joint Asset Returns and Portfolio Risk',
    href: '/topics/application-modeling-joint-asset-returns',
    icon: Waypoints,
    description: 'Using the multivariate normal distribution to model asset returns.',
    category: 'sub-topic',
    parent: 'multivariate-normal-distribution',
  },
];

    