
import { type Topic } from './types';
import { createTopic } from './utils';

export const linearAlgebraPart2: Topic[] = [
    // --- Module 3: Determinants ---
    createTopic({
        parent: 'la-module-3',
        title: 'The Geometric Meaning of the Determinant',
        icon: 'Waypoints',
        description: "The determinant as the scaling factor of area/volume.",
        category: 'sub-topic',
        duration: 20,
    }),
    createTopic({
        parent: 'la-module-3',
        id: 'calculation-and-properties-of-the-determinant',
        title: 'Calculation and Properties',
        icon: 'Waypoints',
        description: "Cofactor expansion and the properties of determinants. A determinant of zero means the matrix squishes space into a lower dimension (i.e., it's not invertible).",
        category: 'sub-topic',
        duration: 30,
    }),

    // --- Module 4: Eigenvalues & Eigendecompositions ---
     createTopic({
        parent: 'la-module-4',
        title: 'Eigenvalues & Eigenvectors',
        icon: 'Waypoints',
        description: "Finding the 'special' vectors that are only scaled by a transformation, not rotated off their span (Ax = λx).",
        category: 'sub-topic',
        duration: 30,
    }),
     createTopic({
        parent: 'la-module-4',
        title: 'The Characteristic Equation',
        icon: 'Waypoints',
        description: "The calculation behind eigenvalues: solving det(A - λI) = 0.",
        category: 'sub-topic',
        duration: 25,
    }),
     createTopic({
        parent: 'la-module-4',
        title: 'Diagonalization (PDP⁻¹)',
        icon: 'Waypoints',
        description: "Decomposing a matrix into its core components: 'changing to the eigenbasis, scaling, and changing back.'",
        category: 'sub-topic',
        duration: 35,
    }),
    createTopic({
        parent: 'la-module-4',
        title: 'Applications of Eigen-analysis',
        icon: 'Waypoints',
        description: 'Using eigenvalues for tasks like calculating matrix powers (e.g., for Markov chains).',
        category: 'sub-topic',
        duration: 25,
    }),
     createTopic({
        parent: 'la-module-4',
        title: 'The Spectral Theorem',
        icon: 'Waypoints',
        description: "For symmetric matrices (like covariance matrices), the eigendecomposition is especially beautiful and stable (A = QDQᵀ). This is the theoretical foundation of PCA.",
        category: 'sub-topic',
        duration: 35,
    }),
    createTopic({
        parent: 'la-module-4',
        title: 'The Cholesky Decomposition (LLᵀ)',
        icon: 'Waypoints',
        description: "A highly efficient specialization for symmetric, positive-definite matrices, often used in optimization and financial modeling.",
        category: 'sub-topic',
        duration: 25,
    }),

    // --- Module 5: Least Squares & QR Decomposition ---
    createTopic({
        parent: 'la-module-5',
        title: 'The Inexact Problem: Why Ax=b Often Has No Solution',
        icon: 'Waypoints',
        description: 'Introducing the goal of minimizing the error ||Ax - b||.',
        category: 'sub-topic',
        duration: 15,
        id: 'the-inexact-problem-ax-b-has-no-solution',
    }),
    createTopic({
        parent: 'la-module-5',
        title: 'The Geometry of "Best Fit": Projections',
        icon: 'Waypoints',
        description: 'Finding the closest point in a subspace (the Column Space) to an external vector.',
        category: 'sub-topic',
        duration: 30,
    }),
    createTopic({
        parent: 'la-module-5',
        title: 'The Algebraic Solution: The Normal Equations',
        icon: 'Waypoints',
        description: 'Deriving AᵀAx̂ = Aᵀb from the projection geometry. This is the engine of Linear Regression.',
        category: 'sub-topic',
        duration: 30,
    }),
    createTopic({
        parent: 'la-module-5',
        title: 'The Problem with the Normal Equations',
        icon: 'Waypoints',
        description: 'Understanding why AᵀA can be ill-conditioned and lead to numerical errors.',
        category: 'sub-topic',
        duration: 15,
    }),
    createTopic({
        parent: 'la-module-5',
        id: 'the-stable-solution-the-gram-schmidt-process',
        title: 'The Stable Solution: The Gram-Schmidt Process',
        icon: 'Waypoints',
        description: 'An algorithm for creating a "nice" orthonormal basis from any starting basis.',
        category: 'sub-topic',
        duration: 35,
    }),
     createTopic({
        parent: 'la-module-5',
        title: 'The QR Decomposition',
        icon: 'Waypoints',
        description: 'Using Gram-Schmidt to factor A=QR. Show how this makes solving the least squares problem trivial (Rx̂ = Qᵀb) and numerically robust.',
        category: 'sub-topic',
        duration: 35,
    }),
    
    // --- Module 6: The Grand Finale - SVD ---
    createTopic({
        parent: 'la-module-6',
        title: 'The Singular Value Decomposition (SVD)',
        icon: 'Waypoints',
        description: 'The ultimate decomposition (A = UΣVᵀ) that works for any matrix and finds orthonormal bases for all four fundamental subspaces simultaneously.',
        category: 'sub-topic',
        duration: 40,
    }),
    createTopic({
        parent: 'la-module-6',
        id: 'principal-component-analysis-pca',
        title: 'Principal Component Analysis (PCA)',
        icon: 'Waypoints',
        description: 'A direct, powerful application of SVD on the data matrix for dimensionality reduction.',
        category: 'sub-topic',
        duration: 30,
    }),
    createTopic({
        parent: 'la-module-6',
        title: 'Advanced SVD Applications',
        icon: 'Waypoints',
        description: 'Low-rank approximation for noise reduction, and the core ideas behind recommendation systems.',
        category: 'sub-topic',
        duration: 25,
    }),

    // --- Module 7: Applications in Finance ---
    createTopic({
        parent: 'la-module-7',
        id: 'the-covariance-matrix-and-the-geometry-of-portfolio-risk',
        title: 'The Covariance Matrix & Portfolio Risk',
        icon: 'Waypoints',
        description: 'Deriving portfolio variance from first principles using linear algebra.',
        category: 'sub-topic',
        duration: 30,
    }),
    createTopic({
        parent: 'la-module-7',
        title: 'Portfolio Optimization & The Efficient Frontier',
        icon: 'Waypoints',
        description: 'Using linear algebra to construct optimal portfolios.',
        category: 'sub-topic',
        duration: 25,
    }),
    createTopic({
        parent: 'la-module-7',
        title: 'The Capital Asset Pricing Model (CAPM)',
        icon: 'Waypoints',
        description: 'Understanding the relationship between risk and expected return.',
        category: 'sub-topic',
        duration: 20,
    }),
     createTopic({
        parent: 'la-module-7',
        title: 'Risk Management & Factor Models',
        icon: 'Waypoints',
        description: 'Decomposing portfolio risk into systematic and idiosyncratic components.',
        category: 'sub-topic',
        duration: 15,
    }),
    createTopic({
        parent: 'la-module-7',
        title: 'Arbitrage & The Fundamental Theorem of Asset Pricing',
        icon: 'Waypoints',
        description: 'The role of linear algebra in proving no-arbitrage conditions.',
        category: 'sub-topic',
        duration: 15,
    }),
    createTopic({
        parent: 'la-module-7',
        title: 'Fixed Income (Bond) Mathematics',
        icon: 'Waypoints',
        description: 'Duration and convexity as linear algebraic concepts.',
        category: 'sub-topic',
        duration: 15,
    }),
];
