
import { type Topic } from './types';
import { createTopic } from './utils';

export const linearAlgebraPart1: Topic[] = [
    // --- Module 1: Foundations of Vectors & Matrices ---
    createTopic({
        parent: 'la-module-1',
        title: 'The Two Views of a Vector',
        icon: 'Waypoints',
        description: "Vectors as geometric arrows vs. vectors as ordered lists of numbers (the data science view).",
        category: 'sub-topic',
        duration: 15,
        status: 'completed',
    }),
    createTopic({
        parent: 'la-module-1',
        title: 'Vector Operations',
        icon: 'Waypoints',
        description: "Addition, subtraction (tip-to-tail rule), and scalar multiplication (stretching/shrinking).",
        category: 'sub-topic',
        duration: 20,
        status: 'in-progress',
    }),
    createTopic({
        parent: 'la-module-1',
        title: 'The Dot Product, Norms, and Angles',
        icon: 'Waypoints',
        description: "The dot product as a measure of 'projection' or 'agreement.' L1 and L2 norms as measures of length/magnitude. Cosine similarity as a practical application.",
        category: 'sub-topic',
        duration: 25,
        status: 'not-started',
    }),
    createTopic({
        parent: 'la-module-1',
        title: 'Orthogonality',
        icon: 'Waypoints',
        description: "The concept of perpendicular vectors (dot product = 0) and its meaning: independence.",
        category: 'sub-topic',
        duration: 20,
        status: 'not-started',
    }),
    createTopic({
        parent: 'la-module-1',
        title: 'The Two Views of a Matrix',
        icon: 'Waypoints',
        description: "A matrix as a container for data (a collection of vectors) vs. a matrix as a linear transformation that moves, rotates, and scales space.",
        category: 'sub-topic',
        duration: 15,
        status: 'not-started',
    }),
    createTopic({
        parent: 'la-module-1',
        title: 'Matrix Operations',
        icon: 'Waypoints',
        description: "Addition, scalar multiplication, and the transpose.",
        category: 'sub-topic',
        duration: 20,
        status: 'not-started',
    }),
    createTopic({
        parent: 'la-module-1',
        title: 'Matrix Multiplication',
        icon: 'Waypoints',
        description: "Taught not just as a rule, but as the composition of linear transformations. This explains why AB ≠ BA.",
        category: 'sub-topic',
        duration: 25,
        status: 'not-started',
    }),
    createTopic({
        parent: 'la-module-1',
        title: 'Special Matrices',
        icon: 'Waypoints',
        description: "Identity matrix (the 'do nothing' operation), inverse matrix (the 'undo' operation), diagonal, triangular, and symmetric matrices.",
        category: 'sub-topic',
        duration: 20,
        status: 'not-started',
    }),
    createTopic({
        parent: 'la-module-1',
        title: 'Linear Combinations and Span',
        icon: 'Waypoints',
        description: "What can you build with a set of vectors?",
        category: 'sub-topic',
        duration: 20,
        status: 'not-started',
    }),
    createTopic({
        parent: 'la-module-1',
        title: 'Linear Independence',
        icon: 'Waypoints',
        description: "Identifying and removing redundant vectors.",
        category: 'sub-topic',
        duration: 20,
        status: 'not-started',
    }),
    createTopic({
        parent: 'la-module-1',
        title: 'Basis and Dimension',
        icon: 'Waypoints',
        description: "The minimal set of vectors needed to define a space and the concept of its dimension.",
        category: 'sub-topic',
        duration: 25,
        status: 'not-started',
    }),
    createTopic({
        parent: 'la-module-1',
        title: 'Vector Spaces and Subspaces',
        icon: 'Waypoints',
        description: "Formalizing these concepts. A subspace as a 'plane' or 'line' within a higher-dimensional space that passes through the origin.",
        category: 'sub-topic',
        duration: 25,
        status: 'not-started',
    }),

    // --- Module 2: Solving Linear Systems ---
     createTopic({
        parent: 'la-module-2',
        title: 'Framing the Problem: Ax=b',
        icon: 'Waypoints',
        description: "Understanding Ax=b from the row picture (intersection of planes) and the column picture (linear combination of columns).",
        category: 'sub-topic',
        duration: 20,
    }),
     createTopic({
        parent: 'la-module-2',
        title: 'Gaussian Elimination',
        icon: 'Waypoints',
        description: "The core algorithm for solving linear systems. Row operations, row echelon form (REF), and reduced row echelon form (RREF).",
        category: 'sub-topic',
        duration: 25,
    }),
     createTopic({
        parent: 'la-module-2',
        title: 'The Solutions to Ax=b',
        icon: 'Waypoints',
        description: "Identifying if a system has a unique solution, no solution, or infinitely many solutions from its RREF.",
        category: 'sub-topic',
        duration: 20,
    }),
     createTopic({
        parent: 'la-module-2',
        title: 'LU Decomposition',
        icon: 'Waypoints',
        description: "The 'matrix version' of Gaussian Elimination. Solving Ax=b becomes a fast, two-step process of forward and back substitution.",
        category: 'sub-topic',
        duration: 25,
    }),
     createTopic({
        parent: 'la-module-2',
        title: 'Column Space &amp; Rank',
        icon: 'Waypoints',
        description: 'The space of all possible outputs of A. The concept of rank as the "true dimension" of the output space.',
        category: 'sub-topic',
        duration: 15,
    }),
     createTopic({
        parent: 'la-module-2',
        title: 'The Null Space',
        icon: 'Waypoints',
        description: 'The space of all inputs that map to the zero vector. Its connection to multicollinearity in data.',
        category: 'sub-topic',
        duration: 15,
    }),
     createTopic({
        parent: 'la-module-2',
        title: 'Row Space &amp; Left Null Space',
        icon: 'Waypoints',
        description: 'Completing the picture of the four fundamental subspaces.',
        category: 'sub-topic',
        duration: 15,
    }),
     createTopic({
        parent: 'la-module-2',
        title: 'The Fundamental Theorem of Linear Algebra',
        icon: 'Waypoints',
        description: "How the four subspaces relate to each other and partition the input and output spaces.",
        category: 'sub-topic',
        duration: 20,
    }),
];
