
import {
  Pi,
  Sigma,
  BrainCircuit,
  LineChart,
  Cpu,
  CandlestickChart,
  Boxes,
  Percent,
  FlaskConical,
  Wrench,
} from 'lucide-react';
import type { Topic } from './types';

export const mainTopics: Topic[] = [
  {
    id: 'linear-algebra',
    title: 'Linear Algebra',
    description: 'Vectors, matrices, and tensors. The language of data.',
    icon: Pi,
    href: '/linear-algebra',
    category: 'main',
    animation: 'linear-algebra',
  },
  {
    id: 'statistics',
    title: 'Statistical Tests',
    description: 'The science of collecting, analyzing, and interpreting data.',
    icon: Sigma,
    href: '/statistics',
    category: 'main',
    animation: 'statistics',
  },
  {
    id: 'stat-toolkit',
    title: "Statistician's Toolkit",
    description: 'Explore and understand the core concepts of statistics for quantitative analysis.',
    icon: Wrench,
    href: '/stat-toolkit',
    category: 'main',
    animation: 'stat-toolkit',
  },
  {
    id: 'probability',
    title: 'Probability',
    description: 'The mathematical foundation for understanding randomness and uncertainty.',
    icon: Percent,
    href: '/probability',
    category: 'main',
    animation: 'probability',
  },
   {
    id: 'probability-toolkit',
    title: 'Probability Toolkit',
    description: 'An interactive journey through the key distributions in probability theory.',
    icon: FlaskConical,
    href: '/paths/probability-toolkit',
    category: 'main',
    animation: 'probability-toolkit',
  },
  {
    id: 'mental-math',
    title: 'Mental Math',
    description: 'Train your calculation speed and accuracy for interviews.',
    icon: BrainCircuit,
    href: '/mental-math',
    category: 'main',
    animation: 'mental-math',
  },
  {
    id: 'time-series-analysis',
    title: 'Time Series Analysis',
    description: 'ARIMA, GARCH, and forecasting market movements.',
    icon: LineChart,
    href: '/paths/time-series-analysis-for-quantitative-finance',
    category: 'main',
    animation: 'time-series-analysis',
  },
  {
    id: 'machine-learning',
    title: 'Machine Learning',
    description: 'Building predictive models for financial markets.',
    icon: Cpu,
    href: '/paths/machine-learning-for-quantitative-finance',
    category: 'main',
    animation: 'machine-learning',
  },
];
