
import type { Topic } from './types';

export const mainTopics: Topic[] = [
   {
    id: 'quantlab',
    title: 'QuantLab',
    description: 'Interactive tools for hands-on probability and statistics analysis.',
    icon: 'FlaskConical',
    href: '/quantlab',
    category: 'main',
    animation: 'probability-toolkit',
  },
  {
    id: 'mental-math',
    title: 'Mental Math',
    description: 'Train your calculation speed and accuracy for interviews.',
    icon: 'BrainCircuit',
    href: '/topics/mental-math',
    category: 'main',
    animation: 'mental-math',
  },
  {
    id: 'linear-algebra',
    title: 'Linear Algebra',
    description: 'Vectors, matrices, and tensors. The language of data.',
    icon: 'Pi',
    href: '/paths/linear-algebra-for-quantitative-finance',
    category: 'main',
    animation: 'linear-algebra',
  },
  {
    id: 'statistics',
    title: 'Advanced Statistics',
    description: 'The science of collecting, analyzing, and interpreting data.',
    icon: 'BarChart3',
    href: '/paths/statistics-for-quantitative-finance',
    category: 'main',
    animation: 'statistics',
  },
  {
    id: 'probability',
    title: 'Probability for Quants',
    description: 'Master random variables, distributions, and stochastic processes.',
    icon: 'Percent',
    href: '/paths/probability-for-quants',
    category: 'main',
    animation: 'probability',
  },
  {
    id: 'time-series-analysis',
    title: 'Time Series Analysis',
    description: 'ARIMA, GARCH, and forecasting market movements.',
    icon: 'LineChart',
    href: '/paths/time-series-analysis-for-quantitative-finance',
    category: 'main',
    animation: 'time-series-analysis',
  },
  {
    id: 'machine-learning',
    title: 'Machine Learning',
    description: 'Building predictive models for financial markets.',
    icon: 'Cpu',
    href: '/paths/machine-learning-for-quantitative-finance',
    category: 'main',
    animation: 'machine-learning',
  },
];
