
import { type Topic } from './types';

export const probabilityAdvancedTopics: Topic[] = [
    // --- Module 1: Foundations of Probability ---
    {
        id: 'prob-foundations-sample-spaces',
        title: 'The Basics: Sample Spaces & Events',
        href: '/topics/prob-foundations-sample-spaces',
        icon: 'Dice3',
        description: "Understanding the building blocks of probability.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-1',
        duration: 20,
    },
    {
        id: 'prob-foundations-combinatorics',
        title: 'Combinatorics: The Art of Counting',
        href: '/topics/prob-foundations-combinatorics',
        icon: 'Calculator',
        description: "Techniques for counting outcomes and possibilities.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-1',
        duration: 25,
    },
    {
        id: 'prob-foundations-conditional',
        title: 'Conditional Probability & Independence',
        href: '/topics/prob-foundations-conditional',
        icon: 'GitBranch',
        description: "How the occurrence of one event affects another.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-1',
        duration: 20,
    },
    {
        id: 'prob-foundations-bayes',
        title: "Bayes' Theorem",
        href: '/probability/bayes-theorem',
        icon: 'BrainCircuit',
        description: "Updating beliefs in the face of new evidence.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-1',
        duration: 20,
    },

    // --- Module 2: Random Variables & Distributions ---
    {
        id: 'prob-rv-definition',
        title: 'Random Variables (Discrete & Continuous)',
        href: '/topics/prob-rv-definition',
        icon: 'BarChart3',
        description: "Mapping outcomes of a random process to numbers.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-2',
        duration: 20,
    },
    {
        id: 'prob-rv-expectation',
        title: 'Expectation, Variance & Moments',
        href: '/topics/prob-rv-expectation',
        icon: 'Target',
        description: "Calculating the center, spread, and shape of a distribution.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-2',
        duration: 25,
    },
    {
        id: 'prob-rv-discrete-dist',
        title: 'Common Discrete Distributions',
        href: '/topics/prob-rv-discrete-dist',
        icon: 'Component',
        description: "Exploring Bernoulli, Binomial, and Poisson distributions.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-2',
        duration: 30,
    },
    {
        id: 'prob-rv-continuous-dist',
        title: 'Common Continuous Distributions',
        href: '/topics/prob-rv-continuous-dist',
        icon: 'AreaChart',
        description: "Exploring Uniform, Normal, and Exponential distributions.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-2',
        duration: 25,
    },

    // --- Module 3: Multivariate Probability & Core Theorems ---
    {
        id: 'prob-multi-joint',
        title: 'Joint, Marginal & Conditional Distributions',
        href: '/topics/prob-multi-joint',
        icon: 'Users',
        description: "Modeling the behavior of multiple random variables at once.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-3',
        duration: 30,
    },
    {
        id: 'prob-multi-covariance',
        title: 'Covariance & Correlation',
        href: '/topics/pearson-correlation',
        icon: 'TrendingUp',
        description: "Measuring how two random variables move together.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-3',
        duration: 25,
    },
    {
        id: 'prob-multi-lln',
        title: 'The Law of Large Numbers (LLN)',
        href: '/topics/law-of-large-numbers',
        icon: 'Scale',
        description: "Why casino averages are so stable.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-3',
        duration: 20,
    },
    {
        id: 'prob-multi-clt',
        title: 'The Central Limit Theorem (CLT)',
        href: '/topics/central-limit-theorem',
        icon: 'Bell',
        description: "Why the normal distribution is everywhere.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-3',
        duration: 30,
    },

    // --- Module 4: Intermediate Topics & Generating Functions ---
    {
        id: 'prob-inter-transformations',
        title: 'Transformations of Random Variables',
        href: '/topics/prob-inter-transformations',
        icon: 'Replace',
        description: "Finding the distribution of a function of a random variable.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-4',
        duration: 30,
    },
    {
        id: 'prob-inter-mgf',
        title: 'Moment Generating Functions (MGFs)',
        href: '/topics/prob-inter-mgf',
        icon: 'Sun',
        description: "A powerful tool for analyzing distributions.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-4',
        duration: 30,
    },
    {
        id: 'prob-inter-info-theory',
        title: 'Introduction to Information Theory',
        href: '/topics/prob-inter-info-theory',
        icon: 'Binary',
        description: "Quantifying information with Entropy and KL Divergence.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-4',
        duration: 30,
    },

    // --- Module 5: Stochastic Processes ---
    {
        id: 'prob-stochastic-intro',
        title: 'Introduction to Stochastic Processes & Stationarity',
        href: '/topics/prob-stochastic-intro',
        icon: 'Clock',
        description: "Understanding random phenomena that evolve over time.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-5',
        duration: 20,
    },
    {
        id: 'prob-stochastic-markov',
        title: 'Discrete-Time Markov Chains',
        href: '/topics/prob-stochastic-markov',
        icon: 'Footprints',
        description: "Modeling memoryless state transitions.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-5',
        duration: 40,
    },
    {
        id: 'prob-stochastic-poisson',
        title: 'The Poisson Process',
        href: '/probability/poisson-distribution',
        icon: 'Zap',
        description: "Modeling the timing of random events.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-5',
        duration: 30,
    },
    {
        id: 'prob-stochastic-brownian',
        title: 'Random Walks & Brownian Motion',
        href: '/topics/prob-stochastic-brownian',
        icon: 'TrendingDown',
        description: "The mathematical foundation of stock price movements.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-5',
        duration: 30,
    },

    // --- Module 6: Advanced & Measure-Theoretic Probability ---
    {
        id: 'prob-advanced-sigma-algebras',
        title: 'Sigma-Algebras & Probability Measures',
        href: '/topics/prob-advanced-sigma-algebras',
        icon: 'Ruler',
        description: "The rigorous foundation of modern probability.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-6',
        duration: 35,
    },
    {
        id: 'prob-advanced-lebesgue',
        title: 'The Lebesgue Integral & Rigorous Expectation',
        href: '/topics/prob-advanced-lebesgue',
        icon: 'PenTool',
        description: "A more powerful theory of integration.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-6',
        duration: 35,
    },
    {
        id: 'prob-advanced-martingales',
        title: 'Martingales',
        href: '/topics/prob-advanced-martingales',
        icon: 'Scale',
        description: "The formal model of a fair game.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-6',
        duration: 40,
    },
    {
        id: 'prob-advanced-ito',
        title: "Introduction to Itô Calculus",
        href: '/topics/stochastic-calculus-itos-lemma',
        icon: 'AreaChart',
        description: "The calculus of random walks, essential for derivatives pricing.",
        category: 'sub-topic',
        parent: 'prob-quant-mod-6',
        duration: 40,
    },
];
