import { FunctionSquare } from 'lucide-react';
import type { Topic } from './types';

export const probabilityTopics: Topic[] = [
  {
    id: 'bayes-theorem',
    title: "Bayes' Theorem",
    href: '/probability/bayes-theorem',
    icon: FunctionSquare,
    description: 'A framework for updating beliefs with new evidence.',
    category: 'probability',
    parent: 'probability',
  },
  {
    id: 'law-of-large-numbers',
    title: 'The Law of Large Numbers',
    href: '/topics/law-of-large-numbers',
    icon: FunctionSquare,
    description: 'How randomness converges to predictability.',
    category: 'probability',
    parent: 'stats-intermediate',
  },
  {
    id: 'binomial-distribution',
    title: 'Binomial Distribution',
    href: '/probability/binomial-distribution',
    icon: FunctionSquare,
    description: 'Modeling a series of success/fail trials.',
    category: 'probability',
    parent: 'stats-intermediate',
  },
  {
    id: 'poisson-distribution',
    title: 'Poisson Distribution',
    href: '/probability/poisson-distribution',
    icon: FunctionSquare,
    description: 'Modeling the frequency of rare events.',
    category: 'probability',
    parent: 'stats-intermediate',
  },
  {
    id: 'gamma-distribution',
    title: 'Gamma Distribution',
    href: '/probability/gamma-distribution',
    icon: FunctionSquare,
    description: 'Modeling waiting times and skewed data.',
    category: 'probability',
    parent: 'stats-intermediate',
  },
  {
    id: 'moment-generating-functions',
    title: 'Moment Generating Functions',
    href: '/probability/moment-generating-functions',
    icon: FunctionSquare,
    description: '',
    category: 'probability',
    parent: 'probability',
  },
  {
    id: 'maximum-likelihood-estimation',
    title: 'Maximum Likelihood Estimation (MLE)',
    href: '/probability/maximum-likelihood-estimation',
    icon: FunctionSquare,
    description: '',
    category: 'probability',
    parent: 'probability',
  },
];
