
import type { Topic } from './types';
import { createTopic } from './utils';

export const probabilityTopics: Topic[] = [
  createTopic({
    id: 'bayes-theorem-interactive-guide',
    title: "Bayes' Theorem",
    icon: 'BrainCircuit',
    description: 'A framework for updating beliefs with new evidence.',
    category: 'probability',
    parent: 'prob-core-tools',
    pathPrefix: 'quantlab',
    seoTitle: "Bayes' Theorem Explained: An Interactive Guide",
    metaDescription: "Learn the intuition behind Bayes' Theorem and the base rate fallacy with an interactive calculator and visual guide for this core quantitative finance concept."
  }),
  createTopic({
    id: 'bernoulli-distribution-interactive-guide',
    title: 'Bernoulli Distribution',
    icon: 'ToggleRight',
    description: 'Modeling a single trial with two outcomes.',
    category: 'probability',
    parent: 'prob-dist-discrete',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'binomial-distribution-interactive-guide',
    title: 'Binomial Distribution',
    icon: 'BarChartBig',
    description: 'Modeling a series of success/fail trials.',
    category: 'probability',
    parent: 'prob-dist-discrete',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'poisson-distribution-interactive-guide',
    title: 'Poisson Distribution',
    icon: 'Clock4',
    description: 'Modeling the frequency of rare events.',
    category: 'probability',
    parent: 'prob-dist-discrete',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'geometric-distribution-interactive-guide',
    title: 'Geometric Distribution',
    icon: 'Repeat1',
    description: 'Modeling trials until the first success.',
    category: 'probability',
    parent: 'prob-dist-discrete',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'hypergeometric-distribution-interactive-guide',
    title: 'Hypergeometric Distribution',
    icon: 'Ungroup',
    description: 'Modeling sampling without replacement.',
    category: 'probability',
    parent: 'prob-dist-discrete',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'negative-binomial-distribution-interactive-guide',
    title: 'Negative Binomial Distribution',
    icon: 'Repeat',
    description: 'Modeling trials until a set number of successes.',
    category: 'probability',
    parent: 'prob-dist-discrete',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'discrete-uniform-distribution-interactive-guide',
    title: 'Discrete Uniform Distribution',
    icon: 'Dice3',
    description: 'Modeling where all outcomes are equally likely.',
    category: 'probability',
    parent: 'prob-dist-discrete',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'multinomial-distribution-interactive-guide',
    title: 'Multinomial Distribution',
    icon: 'Boxes',
    description: 'Generalizing the Binomial for multiple outcomes.',
    category: 'probability',
    parent: 'prob-dist-discrete',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'gamma-distribution-interactive-guide',
    title: 'Gamma Distribution',
    icon: 'Waves',
    description: 'Modeling waiting times and skewed data.',
    category: 'probability',
    parent: 'prob-dist-continuous',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'beta-distribution-interactive-guide',
    title: 'Beta Distribution',
    icon: 'Activity',
    description: 'Modeling probabilities, percentages, and proportions.',
    category: 'probability',
    parent: 'prob-dist-continuous',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'exponential-distribution-interactive-guide',
    title: 'Exponential Distribution',
    icon: 'Timer',
    description: 'Modeling the time between events in a Poisson process.',
    category: 'probability',
    parent: 'prob-dist-continuous',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'cauchy-distribution-interactive-guide',
    title: 'Cauchy Distribution',
    icon: 'Mountain',
    description: "Modeling extreme events and 'fat-tailed' phenomena.",
    category: 'probability',
    parent: 'prob-dist-continuous',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'laplace-distribution-interactive-guide',
    title: 'Laplace Distribution',
    icon: 'Gem',
    description: "Modeling with a sharp peak and 'fat tails'.",
    category: 'probability',
    parent: 'prob-dist-continuous',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'f-distribution-interactive-guide',
    title: 'F-Distribution',
    icon: 'Ratio',
    description: 'Comparing variances between two or more samples.',
    category: 'probability',
    parent: 'prob-dist-continuous',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'students-t-distribution-interactive-guide',
    title: "Student's t-Distribution",
    icon: 'Users',
    description: 'The backbone of hypothesis testing with small sample sizes.',
    category: 'probability',
    parent: 'prob-dist-continuous',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'weibull-distribution-interactive-guide',
    title: 'Weibull Distribution',
    icon: 'Wind',
    description: 'Modeling time-to-failure and event durations.',
    category: 'probability',
    parent: 'prob-dist-continuous',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'logistic-distribution-interactive-guide',
    title: 'Logistic Distribution',
    icon: 'TrendingUp',
    description: 'A key distribution in machine learning and growth modeling.',
    category: 'probability',
    parent: 'prob-dist-continuous',
    pathPrefix: 'quantlab',
  }),
  createTopic({
    id: 'chi-squared-distribution-interactive-guide',
    title: 'Chi-Squared (χ²) Distribution',
    icon: 'Sigma',
    description: 'The distribution of the sum of squared standard normal deviates.',
    category: 'probability',
    parent: 'prob-dist-continuous',
    pathPrefix: 'quantlab',
  }),
];
