
import type { Topic } from './types';
import { createTopic } from './utils';

export const quantlabStatisticalTools: Topic[] = [
  // Parent "topic" for Hypothesis testing, mainly for grouping in other files
  createTopic({
    id: 'hypothesis-testing',
    href: '/quantlab/hypothesis-testing-guide',
    parent: 'stats-advanced-tools',
    title: 'Hypothesis Testing & P-Values',
    icon: 'FunctionSquare',
    description: 'The detective work of data science.',
    category: 'sub-topic',
  }),
  // Tier 1 Lessons
  createTopic({
    id: 'descriptive-statistics-explorer',
    href: '/quantlab/descriptive-statistics-explorer',
    parent: 'prob-core-tools',
    title: 'Descriptive Statistics Explorer',
    icon: 'BarChartHorizontal',
    description: 'Interactive guide to mean, median, skewness, and kurtosis.',
    category: 'probability',
  }),
  createTopic({
    id: 'central-limit-theorem',
    href: '/quantlab/central-limit-theorem',
    parent: 'prob-core-tools',
    title: 'The Central Limit Theorem (CLT)',
    icon: 'Bell',
    description: 'Discover how order emerges from chaos.',
    category: 'probability',
  }),
  createTopic({
    id: 'confidence-intervals',
    href: '/quantlab/confidence-intervals',
    parent: 'prob-core-tools',
    title: 'Confidence Intervals',
    icon: 'Target',
    description: 'Understanding the range where a true value likely lies.',
    category: 'sub-topic',
  }),
  createTopic({
    id: 'z-table',
    href: '/quantlab/z-table',
    parent: 'prob-core-tools',
    title: 'Z-Table Calculator',
    icon: 'Table',
    description: 'Calculate probabilities from Z-scores and vice-versa.',
    category: 'sub-topic',
  }),
  createTopic({
    id: 'normal-distribution',
    href: '/quantlab/normal-distribution',
    parent: 'prob-dist-continuous',
    title: 'The Normal Distribution',
    icon: 'Bell',
    description: 'The ubiquitous "bell curve."',
    category: 'probability',
  }),

  // Tier 3 Lessons
  createTopic({
    id: 'monte-carlo-simulation',
    href: '/quantlab/monte-carlo-simulation',
    parent: 'stats-advanced-tools',
    title: 'Monte Carlo Simulation',
    icon: 'Dice',
    description: 'Using random simulation to solve complex problems.',
    category: 'sub-topic',
  }),
  createTopic({
    id: 'time-series-decomposition',
    href: '/quantlab/time-series-decomposition',
    parent: 'stats-advanced-tools',
    title: 'Time Series Decomposition',
    icon: 'Layers',
    description: 'Breaking down a time series into its core components.',
    category: 'sub-topic',
  }),
  createTopic({
    id: 'autocorrelation-acf-pacf',
    href: '/quantlab/autocorrelation-acf-pacf',
    parent: 'stats-advanced-tools',
    title: 'Autocorrelation (ACF & PACF)',
    icon: 'Signal',
    description: 'Measuring how a time series correlates with its past values.',
    category: 'sub-topic',
  }),
  createTopic({
    id: 'volatility-garch',
    href: '/quantlab/volatility-garch',
    parent: 'stats-advanced-tools',
    title: 'Volatility & Standard Deviation (GARCH)',
    icon: 'Flame',
    description: 'Modeling the changing volatility of financial returns.',
    category: 'sub-topic',
  }),
  createTopic({
    id: 'efficient-frontier-sharpe-ratio',
    href: '/quantlab/efficient-frontier-sharpe-ratio',
    parent: 'stats-advanced-tools',
    title: 'Efficient Frontier & Sharpe Ratio',
    icon: 'Target',
    description: 'Finding the optimal portfolio for a given level of risk.',
    category: 'sub-topic',
  }),
  createTopic({
    id: 'kalman-filters',
    href: '/quantlab/kalman-filters',
    parent: 'stats-advanced-tools',
    title: 'Kalman Filters',
    icon: 'Filter',
    description: 'Dynamically estimating the state of a system from noisy data.',
    category: 'sub-topic',
  }),
  createTopic({
    id: 'stochastic-calculus-itos-lemma',
    href: '/quantlab/stochastic-calculus-itos-lemma',
    parent: 'stats-advanced-tools',
    title: "Stochastic Calculus & Ito's Lemma",
    icon: 'Calculator',
    description: 'The calculus of random walks, essential for derivatives pricing.',
    category: 'sub-topic',
  }),
];
