

import { FunctionSquare, FolderKanban } from 'lucide-react';
import type { Topic } from './types';

export const statisticsTopics: Topic[] = [
  // Parent "topic" for Hypothesis testing
  {
    id: 'hypothesis-testing',
    title: 'Hypothesis Testing',
    href: '/hypothesis-testing',
    icon: FunctionSquare,
    description: 'The detective work of data science.',
    category: 'sub-topic',
    parent: 'statistics-for-quantitative-finance',
  },

  // Parametric Tests (sub-topics of hypothesis testing)
  {
    id: 't-test',
    title: 'T-Test',
    href: '/topics/statistics/t-test',
    icon: FunctionSquare,
    description: 'Compares the means of two groups, assuming normal distribution.',
    category: 'parametric',
    parent: 'hypothesis-testing',
  },
  {
    id: 'z-test',
    title: 'Z-Test',
    href: '/topics/statistics/z-test',
    icon: FunctionSquare,
    description:
      'Compares means of large samples (n>30) with known population variance.',
    category: 'parametric',
    parent: 'hypothesis-testing',
  },
  {
    id: 'anova',
    title: 'ANOVA',
    href: '/topics/statistics/anova',
    icon: FunctionSquare,
    description: 'Compares the averages of three or more groups.',
    category: 'parametric',
    parent: 'hypothesis-testing',
  },
  {
    id: 'f-test',
    title: 'F-Test',
    href: '/topics/statistics/f-test',
    icon: FunctionSquare,
    description: 'Compares the variances (spread) of two or more groups.',
    category: 'parametric',
    parent: 'hypothesis-testing',
  },
  {
    id: 'pearson-correlation',
    title: 'Pearson Correlation',
    href: '/topics/statistics/pearson-correlation',
    icon: FunctionSquare,
    description:
      'Measures the linear relationship between two continuous variables.',
    category: 'parametric',
    parent: 'hypothesis-testing',
  },
  {
    id: 'chi-squared-test',
    title: 'Chi-Squared Test',
    href: '/topics/statistics/chi-squared-test',
    icon: FunctionSquare,
    description:
      'Analyzes categorical data to find significant relationships.',
    category: 'non-parametric',
    parent: 'prob-cat-tests',
  },

  // Non-Parametric Tests (sub-topics of hypothesis testing)
  {
    id: 'mann-whitney-u-test',
    title: 'Mann-Whitney U Test',
    href: '/topics/statistics/mann-whitney-u-test',
    icon: FunctionSquare,
    description:
      'Alternative to the T-Test when data is not normally distributed.',
    category: 'non-parametric',
    parent: 'hypothesis-testing',
  },
  {
    id: 'kruskal-wallis-test',
    title: 'Kruskal-Wallis Test',
    href: '/topics/statistics/kruskal-wallis-test',
    icon: FunctionSquare,
    description: 'Alternative to ANOVA for comparing three or more groups.',
    category: 'non-parametric',
    parent: 'hypothesis-testing',
  },
  {
    id: 'wilcoxon-signed-rank-test',
    title: 'Wilcoxon Signed-Rank Test',
    href: '/topics/statistics/wilcoxon-signed-rank-test',
    icon: FunctionSquare,
    description:
      'Alternative to the paired T-Test for repeated measurements.',
    category: 'non-parametric',
    parent: 'hypothesis-testing',
  },
  {
    id: 'spearmans-rank-correlation',
    title: "Spearman's Rank Correlation",
    href: '/topics/statistics/spearmans-rank-correlation',
    icon: FunctionSquare,
    description:
      'Measures the monotonic relationship between two ranked variables.',
    category: 'non-parametric',
    parent: 'hypothesis-testing',
  },
  {
    id: 'friedman-test',
    title: 'Friedman Test',
    href: '/topics/statistics/friedman-test',
    icon: FunctionSquare,
    description:
      'The non-parametric alternative to a repeated-measures ANOVA.',
    category: 'non-parametric',
    parent: 'hypothesis-testing',
  },
  {
    id: 'kolmogorov-smirnov-k-s-test',
    title: 'Kolmogorov-Smirnov (K-S) Test',
    href: '/topics/statistics/kolmogorov-smirnov-k-s-test',
    icon: FunctionSquare,
    description: 'Tests if a sample is drawn from a specific distribution.',
    category: 'non-parametric',
    parent: 'hypothesis-testing',
  },

  // Stat Toolkit Parent Categories
  {
    id: 'stats-foundations',
    title: 'Tier 1: The Absolute Foundations',
    href: '#',
    icon: FolderKanban,
    description: '',
    category: 'parent',
  },
  {
    id: 'stats-intermediate',
    title: 'Tier 2: Intermediate & Specialized Tools',
    href: '#',
    icon: FolderKanban,
    description: '',
    category: 'parent',
  },
  {
    id: 'stats-advanced',
    title: 'Tier 3: Advanced & Quant-Specific Concepts',
    href: '#',
    icon: FolderKanban,
    description: '',
    category: 'parent',
  },
    
  // Stat Toolkit Tier 1
  {
    id: 'confidence-intervals',
    title: 'Confidence Intervals',
    href: '/topics/confidence-intervals',
    icon: FunctionSquare,
    description: 'Understanding the range where a true value likely lies.',
    category: 'sub-topic',
    parent: 'stats-foundations',
  },
  {
    id: 'descriptive-statistics-explorer',
    title: 'Descriptive Statistics Explorer',
    href: '/topics/statistics/descriptive-statistics-explorer',
    icon: FunctionSquare,
    description: 'Interactive guide to mean, median, mode, variance, skewness, and kurtosis.',
    category: 'sub-topic',
    parent: 'stats-foundations',
  },
  {
    id: 'normal-distribution',
    title: 'The Normal Distribution',
    href: '/topics/statistics/normal-distribution',
    icon: FunctionSquare,
    description: 'The ubiquitous "bell curve."',
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
  {
    id: 'central-limit-theorem',
    title: 'The Central Limit Theorem (CLT)',
    href: '/topics/central-limit-theorem',
    icon: FunctionSquare,
    description: 'Discover how order emerges from chaos.',
    category: 'sub-topic',
    parent: 'stats-foundations',
  },
  {
    id: 'type-i-and-type-ii-errors',
    title: 'Type I & Type II Errors',
    href: '/topics/type-i-and-type-ii-errors',
    icon: FunctionSquare,
    description: 'The trade-off between false alarms and missed signals.',
    category: 'sub-topic',
    parent: 'stats-foundations',
  },
  {
    id: 'correlation-vs-causation',
    title: 'Correlation vs. Causation',
    href: '/topics/correlation-vs-causation',
    icon: FunctionSquare,
    description: "Don't confuse association with influence.",
    category: 'sub-topic',
    parent: 'stats-foundations',
  },
  {
    id: 'linear-regression',
    title: 'Linear Regression',
    href: '/topics/linear-regression',
    icon: FunctionSquare,
    description: 'Modeling the relationship between variables.',
    category: 'sub-topic',
    parent: 'stats-foundations',
  },

  // Stat Toolkit Tier 2
  {
    id: 'logistic-regression',
    title: 'Logistic Regression',
    href: '/topics/statistics/logistic-regression',
    icon: FunctionSquare,
    description: '',
    category: 'sub-topic',
    parent: 'stats-intermediate',
  },

  // Stat Toolkit Tier 3
  {
    id: 'monte-carlo-simulation',
    title: 'Monte Carlo Simulation',
    href: '/topics/monte-carlo-simulation',
    icon: FunctionSquare,
    description: '',
    category: 'sub-topic',
    parent: 'stats-advanced',
  },
  {
    id: 'time-series-decomposition',
    title: 'Time Series Decomposition',
    href: '/topics/statistics/time-series-decomposition',
    icon: FunctionSquare,
    description: '',
    category: 'sub-topic',
    parent: 'stats-advanced',
  },
  {
    id: 'autocorrelation-acf-pacf',
    title: 'Autocorrelation (ACF & PACF)',
    href: '/topics/statistics/autocorrelation-acf-pacf',
    icon: FunctionSquare,
    description: '',
    category: 'sub-topic',
    parent: 'stats-advanced',
  },
  {
    id: 'volatility-garch',
    title: 'Volatility &amp; Standard Deviation (GARCH)',
    href: '/topics/statistics/volatility-garch',
    icon: FunctionSquare,
    description: '',
    category: 'sub-topic',
    parent: 'stats-advanced',
  },
  {
    id: 'efficient-frontier-sharpe-ratio',
    title: 'Efficient Frontier &amp; Sharpe Ratio',
    href: '/topics/statistics/efficient-frontier-sharpe-ratio',
    icon: FunctionSquare,
    description: '',
    category: 'sub-topic',
    parent: 'stats-advanced',
  },
  {
    id: 'kalman-filters',
    title: 'Kalman Filters',
    href: '/topics/statistics/kalman-filters',
    icon: FunctionSquare,
    description: '',
    category: 'sub-topic',
    parent: 'stats-advanced',
  },
  {
    id: 'stochastic-calculus-itos-lemma',
    title: "Stochastic Calculus &amp; Ito's Lemma",
    href: '/topics/statistics/stochastic-calculus-itos-lemma',
    icon: FunctionSquare,
    description: '',
    category: 'sub-topic',
    parent: 'stats-advanced',
  },
];
