
import type { Topic } from './types';

export const probabilityTopics: Topic[] = [
  {
    id: 'bayes-theorem',
    title: "Bayes' Theorem",
    href: '/probability/bayes-theorem',
    icon: 'FunctionSquare',
    description: 'A framework for updating beliefs with new evidence.',
    category: 'probability',
    parent: 'prob-core-tools',
  },
  {
    id: 'law-of-large-numbers',
    title: 'The Law of Large Numbers',
    href: '/topics/law-of-large-numbers',
    icon: 'FunctionSquare',
    description: 'How randomness converges to predictability.',
    category: 'probability',
    parent: 'prob-core-tools',
  },
  {
    id: 'bernoulli-distribution',
    title: 'Bernoulli Distribution',
    href: '/probability/bernoulli-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling a single trial with two outcomes.',
    category: 'probability',
    parent: 'prob-dist-discrete',
  },
  {
    id: 'binomial-distribution',
    title: 'Binomial Distribution',
    href: '/probability/binomial-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling a series of success/fail trials.',
    category: 'probability',
    parent: 'prob-dist-discrete',
  },
  {
    id: 'poisson-distribution',
    title: 'Poisson Distribution',
    href: '/probability/poisson-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling the frequency of rare events.',
    category: 'probability',
    parent: 'prob-dist-discrete',
  },
  {
    id: 'geometric-distribution',
    title: 'Geometric Distribution',
    href: '/probability/geometric-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling trials until the first success.',
    category: 'probability',
    parent: 'prob-dist-discrete',
  },
  {
    id: 'hypergeometric-distribution',
    title: 'Hypergeometric Distribution',
    href: '/probability/hypergeometric-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling sampling without replacement.',
    category: 'probability',
    parent: 'prob-dist-discrete',
  },
  {
    id: 'negative-binomial-distribution',
    title: 'Negative Binomial Distribution',
    href: '/probability/negative-binomial-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling trials until a set number of successes.',
    category: 'probability',
    parent: 'prob-dist-discrete',
  },
  {
    id: 'discrete-uniform-distribution',
    title: 'Discrete Uniform Distribution',
    href: '/probability/discrete-uniform-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling where all outcomes are equally likely.',
    category: 'probability',
    parent: 'prob-dist-discrete',
  },
  {
    id: 'multinomial-distribution',
    title: 'Multinomial Distribution',
    href: '/probability/multinomial-distribution',
    icon: 'FunctionSquare',
    description: 'Generalizing the Binomial for multiple outcomes.',
    category: 'probability',
    parent: 'prob-dist-discrete',
  },
  {
    id: 'gamma-distribution',
    title: 'Gamma Distribution',
    href: '/probability/gamma-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling waiting times and skewed data.',
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
  {
    id: 'beta-distribution',
    title: 'Beta Distribution',
    href: '/probability/beta-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling probabilities, percentages, and proportions.',
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
  {
    id: 'exponential-distribution',
    title: 'Exponential Distribution',
    href: '/probability/exponential-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling the time between events in a Poisson process.',
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
  {
    id: 'cauchy-distribution',
    title: 'Cauchy Distribution',
    href: '/probability/cauchy-distribution',
    icon: 'FunctionSquare',
    description: "Modeling extreme events and 'fat-tailed' phenomena.",
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
  {
    id: 'laplace-distribution',
    title: 'Laplace Distribution',
    href: '/probability/laplace-distribution',
    icon: 'FunctionSquare',
    description: "Modeling with a sharp peak and 'fat tails'.",
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
  {
    id: 'lognormal-distribution',
    title: 'Lognormal Distribution',
    href: '/topics/statistics/lognormal-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling variables that cannot be negative, like stock prices.',
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
  {
    id: 'f-distribution',
    title: 'F-Distribution',
    href: '/probability/f-distribution',
    icon: 'FunctionSquare',
    description: 'Comparing variances between two or more samples.',
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
  {
    id: 'students-t-distribution',
    title: "Student's t-Distribution",
    href: '/probability/students-t-distribution',
    icon: 'FunctionSquare',
    description: 'The backbone of hypothesis testing with small sample sizes.',
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
  {
    id: 'weibull-distribution',
    title: 'Weibull Distribution',
    href: '/probability/weibull-distribution',
    icon: 'FunctionSquare',
    description: 'Modeling time-to-failure and event durations.',
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
  {
    id: 'logistic-distribution',
    title: 'Logistic Distribution',
    href: '/probability/logistic-distribution',
    icon: 'FunctionSquare',
    description: 'A key distribution in machine learning and growth modeling.',
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
  {
    id: 'chi-squared-distribution',
    title: 'Chi-Squared (χ²) Distribution',
    href: '/probability/chi-squared-distribution',
    icon: 'FunctionSquare',
    description: 'The distribution of the sum of squared standard normal deviates.',
    category: 'probability',
    parent: 'prob-dist-continuous',
  },
];
